#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x3602B07F55D0C732 (gray@gnu.org)
#
Name     : tar
Version  : 1.29
Release  : 22
URL      : http://ftp.gnu.org/gnu/tar/tar-1.29.tar.xz
Source0  : http://ftp.gnu.org/gnu/tar/tar-1.29.tar.xz
Source99 : http://ftp.gnu.org/gnu/tar/tar-1.29.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+
Requires: tar-bin
Requires: tar-doc
Requires: tar-locales
Requires: xz-bin
Requires: zstd-bin
BuildRequires : acl-dev
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : bison
BuildRequires : gettext-bin
BuildRequires : glibc-staticdev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
Patch1: CVE-2016-6321.patch
Patch2: timestamp.patch
Patch3: add-zstd.patch
Patch4: blocking.patch

%description
See the end of file for copying conditions.
* Introduction
Please glance through *all* sections of this
'ABOUT-NLS' and 'INSTALL' if you are not familiar with them already.

%package bin
Summary: bin components for the tar package.
Group: Binaries

%description bin
bin components for the tar package.


%package doc
Summary: doc components for the tar package.
Group: Documentation

%description doc
doc components for the tar package.


%package locales
Summary: locales components for the tar package.
Group: Default

%description locales
locales components for the tar package.


%prep
%setup -q -n tar-1.29
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525049846
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs "
%reconfigure --disable-static LDFLAGS=-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1525049846
rm -rf %{buildroot}
%make_install
%find_lang tar

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tar
/usr/libexec/rmt

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man8/*

%files locales -f tar.lang
%defattr(-,root,root,-)

